version: "3.5"

x-args: &default_args
  COMPOSER_VERSION: ${COMPOSER_VERSION:-latest}
  CADDY_VERSION: ${CADDY_VERSION:-latest}
  NODE_VERSION: ${NODE_VERSION:-lts}
  PHP_VERSION: ${PHP_VERSION:-latest}

services:
  server:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: server_caddy
      args: *default_args
    depends_on:
      - backend
###> Prod
#    labels:
#      traefik.http.routers.${PROJECT_NAME}.rule: Host(`${PROJECT_NAME}.anagraph.org`)
#    networks:
#      - proxy
#      - default
###< Prod
    volumes:
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
###> Dev
      - ./:/app
    ports:
      - "443:443"
###< Dev

  backend:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: backend_php
      args: *default_args
    depends_on:
      - database
###> Dev
    volumes:
      - ./:/app
###< Dev

  database:
    image: postgres:${DB_VERSION:-latest}-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
###> Dev
    ports:
      - "5432:5432"
###< Dev

###> Prod
#networks:
#  proxy:
#    external:
#      name: reverse_proxy_network
###< Prod

volumes:
  pgdata:
  caddy_data:
  caddy_config: